// <auto-generated />
namespace LogiGear.Infrastructure.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201606221557568_add-user-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
